#! /bin/sh

#    ____ ____  ______        ____  __ 
#   | __ ) ___||  _ \ \      / /  \/  |  - corro69
#   |  _ \___ \| |_) \ \ /\ / /| |\/| |  - https://github.com/corro69/
#   | |_) |__) |  __/ \ V  V / | |  | |  - massconceptz.com
#   |____/____/|_|     \_/\_/  |_|  |_|
#                                    

########### Def vars

#PATH="$HOME/.config/bspwm/scripts:$PATH"

########### Workspaces

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		let name++
	done
}

workspaces

#AutoStartApps
sxhkd &
picom --experimental-backends -b &
nitrogen --restore &

polybar -c ~/.config/polybar/config.ini bspwm &
#python3 ~/git/my_bar/mybar.py &
# ~/.config/bspwm/mybar.sh &

#$HOME/.config/polybar/bar.sh
########### bspwm conf

bspc config external_rules_command ~/.config/bspwm/scripts/external_rules
bspc config window_gap                    20
bspc config top_padding			  20
bspc config border_width		  2
#bspc config normal _border_color
bspc config active_border_color		  "#ad2ae4" 

bspc config single_monocle                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled		  true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       16

